### ISSUE TITLE
Project name is being stored twice

### ISSUE THREAD

**Issue by jasondkiesling** [engaging-computing/MYR#114]
Within Firebase, the name is stored as a top level field as well as a field under settings

**Comment by CBernsCode** [comment]
I am currently working on trying to refactor the reducers and actions. It has gotten a bit unwieldy, I'll try and give this a bit of attention.

**Comment by jasondkiesling** [comment]
This is fixed for future projects in #142. If a project has a name stored twice, it will still have an extra name stored in settings.

TODO: Create a filter to remove the second name and ID when re-saving a project that has it stored twice.

**Comment by jasondkiesling** [comment]
Resolving this issue involves adding a filter to remove the name key value pair from the settings object whenever a scene goes through the scene reducer. This is similar to the logic for deleting a scene.
