### ISSUE TITLE
The open project menu requires refresh if redux hasn't finished loading

### ISSUE THREAD

**Issue by jasondkiesling** [engaging-computing/MYR#188]
If you open the project drawer quickly before firebase/redux has finished loading the projects into the state, it appears empty. The user then has to close and reopen the drawer to see the projects.

**Comment by samuel-zuk** [comment]
unassigning this from myself for now, maybe someone with better knowledge of async functions/promises could better figure out a solution. 
some links that might be useful:
https://firebase.google.com/docs/functions/terminate-functions
https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference.html
https://firebase.google.com/docs/reference/js/firebase.firestore.Query.html
