### ISSUE TITLE
Editor overlays when in fullscreen on iPhone browers

### ISSUE THREAD

**Issue by jSwanson99** [engaging-computing/MYR#204]
When in fullscreen on iPhone, the editor is still overlaid on top of the view. Problem exists in both Firefox, Brave (Chromium derivative), and Safari. E.g:

To reproduce: 
1. Go to learnmyr.org on iPhone
2. Leave the editor with code in it open 
3. Go into VR mode

In addition, when in view only mode the save menu sticks out of the side of the screen when in view only or VR mode on iPhones.

To reproduce: 
1. Go to learnmyr.org on iPhone
2. Enter view only mode
3. Either enter landscape mode, or enter VR mode

![IMG_8056 3268](https://user-images.githubusercontent.com/25724767/59117480-dc05ca00-891b-11e9-8e43-a70ce1600f58.png)

**Comment by jasondkiesling** [comment]
Can you answer the following for me so I can track this down?

1. Is the editor opened before opening the view?
2. If so, does the issue occur when you open a view only scene?
3. Is this on dev.learnmyr.org or learnmyr.org?

I tried to reproduce this on my phone but cannot do so (Android 8.0.0).

**Comment by jSwanson99** [comment]
1. This occurs only when the editor is open, however 
2. Some other menu (looks like save menu?) sticks out the side when both in view only, and in the VR mode. I will open another bug report for this. 
3. learnmyr.org

It seems to work fine on Android. I've been trying to dig up info on this and it seems like iPhones make it harder to actually go fullscreen than other devices.

**Comment by jasondkiesling** [comment]
These issues seem to be related to we can keep it as one bug report.

**Comment by jasondkiesling** [comment]
It does appear that the save menu is opening for some reason. I can see part of it in the original screenshot.

**Comment by jasondkiesling** [comment]
https://github.com/aframevr/aframe/issues/3508 It appears that this might be a known security "feature" from iOS. Can you try adding it to the homescreen and see if that resolves it?
