### ISSUE TITLE
Pressing the play button sometimes causes issues if updating an already rendered scene.

### ISSUE THREAD

**Issue by samuel-zuk** [engaging-computing/MYR#227]
This problem can be seen when changing animation cursor properties while the scene is playing, and also when trying to restart an animation that does not loop. These weird problems go away when the scene is stopped and restarted, perhaps it can be fixed by changing the function of the play button to stop the scene before re-rendering it?

**Comment by jasondkiesling** [comment]
This is a known issue. @jSwanson99 is working on it.

**Comment by samuel-zuk** [comment]
gotcha. just wanted to add it to the issues board!
