### ISSUE TITLE
Scene "View in VR" button is drawn over reference, which can cover up "View Example" buttons on smaller screens.

### ISSUE THREAD

**Issue by samuel-zuk** [engaging-computing/MYR#270]
![Screenshot from 2019-06-24 10-33-44](https://user-images.githubusercontent.com/50585524/60027585-bbec3f80-966b-11e9-979d-a7a110e8fdd4.png)
![Screenshot from 2019-06-24 10-34-49](https://user-images.githubusercontent.com/50585524/60027586-bc84d600-966b-11e9-9d44-9711022a05d4.png)

**Comment by jasondkiesling** [comment]
This can probably be fixed by setting the z-index of the reference drawer.
