### ISSUE TITLE
Text function should only take string as an argument

### ISSUE THREAD

**Issue by Jlu18** [engaging-computing/MYR#313]
It probably thinks 0 as a false thus not passing in and render default value

**Comment by jasondkiesling** [comment]
Technically passing an integer in is unsupported behavior as text takes in a string and an integer isn't a string.

**Comment by Jlu18** [comment]
So should we make the function to take only string as an argument and explain in reference page?

**Comment by jasondkiesling** [comment]
Elena is working on the reference page issue. It is a known issue that it's not noted as taking a string. If you want to add something that check's that the argument is a string, you can do so.
