### ISSUE TITLE
Unsaved work notification doesn't work on Firefox

### ISSUE THREAD

**Issue by Codom** [engaging-computing/MYR#342]
**Bug Description:**
When you have unsaved work, a notification should appear whenever you attempt to
leave the page. This behavior seems to only happen on Chrome, and not on Firefox.

**Steps To Reproduce:**
1. Open firefox and navigate to learnmyr.org
1. On a new project in myr, make a simple project
1. Leave the page, and observe that your unsaved work is now gone :(

**Expected behavior:**
A notification that prevents users from accidentally navigating away from unsaved work,
permanently deleting it.

**Desktop:**
 - OS: Tested on Windows and Ubuntu
 - Browser firefox
 - Version 67

**Smartphone/VR Headset:**
N/A

**Comment by jasondkiesling** [comment]
Issue reproduced on Firefox 68.0 on Windows 10. Working on fix.

**Comment by jasondkiesling** [comment]
Fix deployed to dev.learnmyr.org and confirmed as working on Firefox on Windows 10.
