### ISSUE TITLE
Partially finished light primitive crashes MYR

### ISSUE THREAD

**Issue by beewyka819** [engaging-computing/MYR#439]
If the user calls light(), MYR crashes. The issue seems to be related to the light() function not creating a scale and rotation, and View.js doesn't check against this. However, getting it to work correctly just appears to spawn a cube into the scene that emits no light.

Suggest removing this code.

**Comment by Jlu18** [comment]
This will be removed when we add light feature into MYR

**Comment by kdvalin** [comment]
Closing since light is now in production.  If the bug can be replicated, reopen this issue.
