### ISSUE TITLE
please change default for new project: floor off, grid on

### ISSUE THREAD

**Issue by fgmart** [engaging-computing/MYR#441]
Please change the settings in MYR so that new projects come up with the floor off and the grid on.

This is important so that new users see the grid and the axes (per below).

Thank you!

![Screen Shot 2021-02-12 at 12 30 41 PM](https://user-images.githubusercontent.com/53866836/107801577-3fb9da80-6d2e-11eb-82cc-2fe6da61e60f.png)

**Comment by kdvalin** [comment]
Impelmented as of 2.3.0
