### ISSUE TITLE
Changing Font size will clear the editor text to the state before

### ISSUE THREAD

**Issue by Jlu18** [engaging-computing/MYR#550]
**Bug Description:**
Changing the fontsize without hitting the render or anything to update the changed user code will result in text to be reverted back to previous state.

**Steps To Reproduce:**
Type anything in MYR without hitting render.
Change the fontsize.
The editor is revert back to empty.

**Expected behavior:**
The text should be remained same after changing the fontsize

**Additional context:**
This is due to the this.props.text not being updated before the editor is being render so the text being is used to render is outdated. One way to solve this problem to use loadash to save the text after the user is finished the keystroke.

**Comment by bryanmontalvan** [comment]
Closed since resolved by #552
