### ISSUE TITLE
App crashes on load when logged in

### ISSUE THREAD

**Issue by jasondkiesling** [engaging-computing/MYR#563]
**Bug Description:**
The app crashes when attempting to visit learnmyr.org while logged in.

**Steps To Reproduce:**
1. Go to learnmyr.org
2. Login as me
3. See the app crash and get a grey screen

**Expected behavior:**
- The app should not crash
- (Ideally also an error boundary to tell me that the app crashed if it did)

**Screenshots:**
<img width="1440" alt="CleanShot 2022-04-24 at 20 41 32@2x" src="https://user-images.githubusercontent.com/32066959/165012039-14feaf01-a163-4418-9b3e-00e0f6597749.png">

**URL(s):**
learnmyr.org

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 100.0.4896.127

**Additional context:**
Confirmed in incognito as well

**Comment by kdvalin** [comment]
Looking into this, cannot get recreate this with my account.

By the looks of it, the project sorting tried sorting a project without a name.  It is possible to have a scene without a name before #372 was merged.

Hotfix in the works

**Comment by kdvalin** [comment]
@jasondkiesling Hotfix #564 is in the pipeline to [dev.learnmyr.org](https://dev.learnmyr.org), mind checking that it works there in ~5 minutes?

**Comment by kdvalin** [comment]
Awesome, working on a patch release for this now.
