### ISSUE TITLE
Development is not possible locally

### ISSUE THREAD

**Issue by wujinhjun** [engaging-computing/MYR#635]
**Bug Description:**  
After I read your paper on the ACM digital, I want to play this project on my Windows. At the same time, I find this project on github. So I git clone.  
When I git clone this project to my desktop(windows), I used the command line `docker build .`. When Run the `npm install`, however, there would have some error:

```
> [4/6] RUN npm install:
#8 0.608 npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
#8 67.09 npm WARN myr@3.1.2 No repository field.
#8 67.09 npm WARN myr@3.1.2 No license field.
#8 67.09
#8 67.18 npm ERR! Error while executing:
#8 67.18 npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/dmarcos/three-buffer-vertex-data.git
#8 67.18 npm ERR!
#8 67.18 npm ERR! Host key verification failed.
#8 67.18 npm ERR! fatal: Could not read from remote repository.
#8 67.18 npm ERR!
#8 67.18 npm ERR! Please make sure you have the correct access rights
#8 67.18 npm ERR! and the repository exists.
#8 67.18 npm ERR!
#8 67.18 npm ERR! exited with error code: 128
#8 95.21
#8 95.21 npm ERR! A complete log of this run can be found in:
#8 95.21 npm ERR!     /root/.npm/_logs/2022-10-14T02_26_04_356Z-debug.log
```
And I changed the `DockerFile` by myself, run `DOCKER_BUILTKIT=1 docker image build -t react-node --ssh default .`:  

```
# syntax=docker/dockerfile:1.0.0-experimental
FROM node:12.18-alpine

WORKDIR /app
COPY . /app

ARG REACT_APP_GOOGLE_CLIENTID="totally invalid.apps.googleusercontent.com"
ENV REACT_APP_GOOGLE_CLIENTID ${REACT_APP_GOOGLE_CLIENTID}

RUN apk add --no-cache openssh-client git
RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh npm install
RUN npm run build
RUN npm run doc
```
Then, the error as below:
```
> [5/7] RUN --mount=type=ssh npm install:
#14 90.43 npm ERR! Error while executing:
#14 90.43 npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/dmarcos/document-register-element.git
#14 90.43 npm ERR!
#14 90.43 npm ERR! Warning: Permanently added the ECDSA host key for IP address '140.82.114.4' to the list of known hosts.
#14 90.43 npm ERR! git@github.com: Permission denied (publickey).
#14 90.43 npm ERR! fatal: Could not read from remote repository.
#14 90.43 npm ERR!
#14 90.43 npm ERR! Please make sure you have the correct access rights
#14 90.43 npm ERR! and the repository exists.
#14 90.43 npm ERR!
#14 90.43 npm ERR! exited with error code: 128
#14 232.1
#14 232.1 npm ERR! A complete log of this run can be found in:
#14 232.1 npm ERR!     /root/.npm/_logs/2022-10-14T02_07_44_466Z-debug.log
```
At this point, I have no solution.  

**Steps To Reproduce:**
1. git clone MYR
2. cd MYR
3. docker build .

Sorry to interrupt, thank you.

**Comment by jf-kelly** [comment]
Hello, thank you for reporting! If I understand your problem correctly, you might have run `docker build` for the front end code, when you only want to do that with the back end. The back end repository is found here: https://github.com/engaging-computing/MYR-backend. Also, check out the wiki for both front end and back end code, as they provide more specific steps for getting set up. Lastly, we recommend setting up a Linux virtual machine to run the code, rather than running it on Windows. Thanks again, and good luck coding!

**Comment by wujinhjun** [comment]
Thank you! At the last, I used the nrm to add an new edition of nodejs. And then this project run successfully on my windows. After time available, I tried building on my linux VM.  
Thank you for your reply!
